In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import imblearn
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks
from imblearn.under_sampling import RandomUnderSampler


from sklearn.model_selection import train_test_split,cross_val_score,StratifiedKFold
from sklearn.metrics import confusion_matrix,classification_report,precision_score, recall_score, f1_score, accuracy_score, matthews_corrcoef
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

from bayes_opt import BayesianOptimization
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [25]:
def writeResultToFile(fileName, result):
    f = open(fileName, "a")
    f.write(result)
    f.close()

In [5]:
dataCSV = pd.read_csv('extracted-all-projects.csv')
vectorCSV = pd.read_csv('vector.csv')

raw = dataCSV['raw']
dataCSV['id']=range(1, len(dataCSV) + 1)
vectorCSV['id']=range(1, len(vectorCSV) + 1)
switchedCSV = vectorCSV[['id','name','feature_0','feature_1','feature_2','feature_3','feature_4','feature_5','feature_6','feature_7','feature_8','feature_9','feature_10','feature_11','feature_12','feature_13','feature_14','feature_15','feature_16','feature_17','feature_18','feature_19','feature_20','feature_21','feature_22','feature_23','feature_24','feature_25','feature_26','feature_27','feature_28','feature_29','feature_30','feature_31','feature_32','feature_33','feature_34','feature_35','feature_36','feature_37','feature_38','feature_39','feature_40','feature_41','feature_42','feature_43','feature_44','feature_45','feature_46','feature_47','feature_48','feature_49','feature_50','feature_51','feature_52','feature_53','feature_54','feature_55','feature_56','feature_57','feature_58','feature_59','feature_60','feature_61','feature_62','feature_63','feature_64','feature_65','feature_66','feature_67','feature_68','feature_69','feature_70','feature_71','feature_72','feature_73','feature_74','feature_75','feature_76','feature_77','feature_78','feature_79','feature_80','feature_81','feature_82','feature_83','feature_84','feature_85','feature_86','feature_87','feature_88','feature_89','feature_90','feature_91','feature_92','feature_93','feature_94','feature_95','feature_96','feature_97','feature_98','feature_99','feature_100','feature_101','feature_102','feature_103','feature_104','feature_105','feature_106','feature_107','feature_108','feature_109','feature_110','feature_111','feature_112','feature_113','feature_114','feature_115','feature_116','feature_117','feature_118','feature_119','feature_120','feature_121','feature_122','feature_123','feature_124','feature_125','feature_126','feature_127','feature_128','feature_129','feature_130','feature_131','feature_132','feature_133','feature_134','feature_135','feature_136','feature_137','feature_138','feature_139','feature_140','feature_141','feature_142','feature_143','feature_144','feature_145','feature_146','feature_147','feature_148','feature_149','feature_150','feature_151','feature_152','feature_153','feature_154','feature_155','feature_156','feature_157','feature_158','feature_159','feature_160','feature_161','feature_162','feature_163','feature_164','feature_165','feature_166','feature_167','feature_168','feature_169','feature_170','feature_171','feature_172','feature_173','feature_174','feature_175','feature_176','feature_177','feature_178','feature_179','feature_180','feature_181','feature_182','feature_183','feature_184','feature_185','feature_186','feature_187','feature_188','feature_189','feature_190','feature_191','feature_192','feature_193','feature_194','feature_195','feature_196','feature_197','feature_198','feature_199','feature_200','feature_201','feature_202','feature_203','feature_204','feature_205','feature_206','feature_207','feature_208','feature_209','feature_210','feature_211','feature_212','feature_213','feature_214','feature_215','feature_216','feature_217','feature_218','feature_219','feature_220','feature_221','feature_222','feature_223','feature_224','feature_225','feature_226','feature_227','feature_228','feature_229','feature_230','feature_231','feature_232','feature_233','feature_234','feature_235','feature_236','feature_237','feature_238','feature_239','feature_240','feature_241','feature_242','feature_243','feature_244','feature_245','feature_246','feature_247','feature_248','feature_249','feature_250','feature_251','feature_252','feature_253','feature_254','feature_255','feature_256','feature_257','feature_258','feature_259','feature_260','feature_261','feature_262','feature_263','feature_264','feature_265','feature_266','feature_267','feature_268','feature_269','feature_270','feature_271','feature_272','feature_273','feature_274','feature_275','feature_276','feature_277','feature_278','feature_279','feature_280','feature_281','feature_282','feature_283','feature_284','feature_285','feature_286','feature_287','feature_288','feature_289','feature_290','feature_291','feature_292','feature_293','feature_294','feature_295','feature_296','feature_297','feature_298','feature_299','feature_300','feature_301','feature_302','feature_303','feature_304','feature_305','feature_306','feature_307','feature_308','feature_309','feature_310','feature_311','feature_312','feature_313','feature_314','feature_315','feature_316','feature_317','feature_318','feature_319','feature_320','feature_321','feature_322','feature_323','feature_324','feature_325','feature_326','feature_327','feature_328','feature_329','feature_330','feature_331','feature_332','feature_333','feature_334','feature_335','feature_336','feature_337','feature_338','feature_339','feature_340','feature_341','feature_342','feature_343','feature_344','feature_345','feature_346','feature_347','feature_348','feature_349','feature_350','feature_351','feature_352','feature_353','feature_354','feature_355','feature_356','feature_357','feature_358','feature_359','feature_360','feature_361','feature_362','feature_363','feature_364','feature_365','feature_366','feature_367','feature_368','feature_369','feature_370','feature_371','feature_372','feature_373','feature_374','feature_375','feature_376','feature_377','feature_378','feature_379','feature_380','feature_381','feature_382','feature_383']]
switchedCSV['category'] = dataCSV['category']
switchedCSV['category'].replace(np.nan, 'NonFlaky', inplace=True)
switchedCSV = switchedCSV[(switchedCSV['category'] == 'ID') | (switchedCSV['category'] == 'UD') |(switchedCSV['category'] == 'OD') | (switchedCSV['category'] == 'OD-Vic') | (switchedCSV['category'] == 'OD-Brit') | (switchedCSV['category'] == 'NOD') | (switchedCSV['category'] == 'NDOD') | (switchedCSV['category'] == 'NODI')]
features = ['feature_0','feature_1','feature_2','feature_3','feature_4','feature_5','feature_6','feature_7','feature_8','feature_9','feature_10','feature_11','feature_12','feature_13','feature_14','feature_15','feature_16','feature_17','feature_18','feature_19','feature_20','feature_21','feature_22','feature_23','feature_24','feature_25','feature_26','feature_27','feature_28','feature_29','feature_30','feature_31','feature_32','feature_33','feature_34','feature_35','feature_36','feature_37','feature_38','feature_39','feature_40','feature_41','feature_42','feature_43','feature_44','feature_45','feature_46','feature_47','feature_48','feature_49','feature_50','feature_51','feature_52','feature_53','feature_54','feature_55','feature_56','feature_57','feature_58','feature_59','feature_60','feature_61','feature_62','feature_63','feature_64','feature_65','feature_66','feature_67','feature_68','feature_69','feature_70','feature_71','feature_72','feature_73','feature_74','feature_75','feature_76','feature_77','feature_78','feature_79','feature_80','feature_81','feature_82','feature_83','feature_84','feature_85','feature_86','feature_87','feature_88','feature_89','feature_90','feature_91','feature_92','feature_93','feature_94','feature_95','feature_96','feature_97','feature_98','feature_99','feature_100','feature_101','feature_102','feature_103','feature_104','feature_105','feature_106','feature_107','feature_108','feature_109','feature_110','feature_111','feature_112','feature_113','feature_114','feature_115','feature_116','feature_117','feature_118','feature_119','feature_120','feature_121','feature_122','feature_123','feature_124','feature_125','feature_126','feature_127','feature_128','feature_129','feature_130','feature_131','feature_132','feature_133','feature_134','feature_135','feature_136','feature_137','feature_138','feature_139','feature_140','feature_141','feature_142','feature_143','feature_144','feature_145','feature_146','feature_147','feature_148','feature_149','feature_150','feature_151','feature_152','feature_153','feature_154','feature_155','feature_156','feature_157','feature_158','feature_159','feature_160','feature_161','feature_162','feature_163','feature_164','feature_165','feature_166','feature_167','feature_168','feature_169','feature_170','feature_171','feature_172','feature_173','feature_174','feature_175','feature_176','feature_177','feature_178','feature_179','feature_180','feature_181','feature_182','feature_183','feature_184','feature_185','feature_186','feature_187','feature_188','feature_189','feature_190','feature_191','feature_192','feature_193','feature_194','feature_195','feature_196','feature_197','feature_198','feature_199','feature_200','feature_201','feature_202','feature_203','feature_204','feature_205','feature_206','feature_207','feature_208','feature_209','feature_210','feature_211','feature_212','feature_213','feature_214','feature_215','feature_216','feature_217','feature_218','feature_219','feature_220','feature_221','feature_222','feature_223','feature_224','feature_225','feature_226','feature_227','feature_228','feature_229','feature_230','feature_231','feature_232','feature_233','feature_234','feature_235','feature_236','feature_237','feature_238','feature_239','feature_240','feature_241','feature_242','feature_243','feature_244','feature_245','feature_246','feature_247','feature_248','feature_249','feature_250','feature_251','feature_252','feature_253','feature_254','feature_255','feature_256','feature_257','feature_258','feature_259','feature_260','feature_261','feature_262','feature_263','feature_264','feature_265','feature_266','feature_267','feature_268','feature_269','feature_270','feature_271','feature_272','feature_273','feature_274','feature_275','feature_276','feature_277','feature_278','feature_279','feature_280','feature_281','feature_282','feature_283','feature_284','feature_285','feature_286','feature_287','feature_288','feature_289','feature_290','feature_291','feature_292','feature_293','feature_294','feature_295','feature_296','feature_297','feature_298','feature_299','feature_300','feature_301','feature_302','feature_303','feature_304','feature_305','feature_306','feature_307','feature_308','feature_309','feature_310','feature_311','feature_312','feature_313','feature_314','feature_315','feature_316','feature_317','feature_318','feature_319','feature_320','feature_321','feature_322','feature_323','feature_324','feature_325','feature_326','feature_327','feature_328','feature_329','feature_330','feature_331','feature_332','feature_333','feature_334','feature_335','feature_336','feature_337','feature_338','feature_339','feature_340','feature_341','feature_342','feature_343','feature_344','feature_345','feature_346','feature_347','feature_348','feature_349','feature_350','feature_351','feature_352','feature_353','feature_354','feature_355','feature_356','feature_357','feature_358','feature_359','feature_360','feature_361','feature_362','feature_363','feature_364','feature_365','feature_366','feature_367','feature_368','feature_369','feature_370','feature_371','feature_372','feature_373','feature_374','feature_375','feature_376','feature_377','feature_378','feature_379','feature_380','feature_381','feature_382','feature_383']
vector_val = switchedCSV[features]
vector_cat = switchedCSV['category']

/var/folders/s8/vyj613fs57b4g86vrn1xc5t80000gn/T/ipykernel_57314/552859148.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  switchedCSV['category'] = dataCSV['category']
/usr/local/lib/python3.9/site-packages/pandas/core/generic.py:6619: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [11]:
print(vector_cat.value_counts())

ID         589
OD         307
OD-Vic     133
NOD        109
UD          93
OD-Brit     15
NDOD        11
Name: category, dtype: int64


In [18]:
smote = SMOTE()
x_smote, y_smote = smote.fit_resample(vector_val, vector_cat)
print(y_smote.value_counts())

ID         589
OD         589
UD         589
OD-Vic     589
OD-Brit    589
NOD        589
NDOD       589
Name: category, dtype: int64


In [19]:
tl = TomekLinks()
X_tl, y_tl = tl.fit_resample(vector_val, vector_cat)
print(y_tl.value_counts())

ID         579
OD         296
OD-Vic     124
NOD         94
UD          84
OD-Brit     11
NDOD        11
Name: category, dtype: int64


In [107]:
X_tl_smote, y_tl_smote = smote.fit_resample(X_tl, y_tl)
print(y_tl_smote.value_counts())
x_smote_tl, y_smote_tl = tl.fit_resample(x_smote, y_smote)
print(y_smote_tl.value_counts())

ID         579
OD         579
UD         579
OD-Vic     579
OD-Brit    579
NOD        579
NDOD       579
Name: category, dtype: int64
ID         589
NDOD       589
OD-Vic     588
OD-Brit    588
OD         587
UD         584
NOD        582
Name: category, dtype: int64


In [105]:
print(y_smote_tl['category'])

KeyError: 'category'

In [83]:
lda = LinearDiscriminantAnalysis(n_components=3)
lda_val = lda.fit_transform(X_tl, y_tl)

X = lda_val
y = y_tl

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
preds = rf.predict(X_test)
print(classification_report(preds,y_test,output_dict=True))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test, average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test, average='weighted'))))

fileName = "sampling_tl.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)


{'ID': {'precision': 0.9137931034482759, 'recall': 0.9034090909090909, 'f1-score': 0.9085714285714287, 'support': 176}, 'NDOD': {'precision': 0.25, 'recall': 1.0, 'f1-score': 0.4, 'support': 1}, 'NOD': {'precision': 0.4642857142857143, 'recall': 0.43333333333333335, 'f1-score': 0.4482758620689655, 'support': 30}, 'OD': {'precision': 0.9438202247191011, 'recall': 0.9130434782608695, 'f1-score': 0.9281767955801105, 'support': 92}, 'OD-Brit': {'precision': 0.3333333333333333, 'recall': 1.0, 'f1-score': 0.5, 'support': 1}, 'OD-Vic': {'precision': 0.918918918918919, 'recall': 0.9714285714285714, 'f1-score': 0.9444444444444445, 'support': 35}, 'UD': {'precision': 0.88, 'recall': 0.88, 'f1-score': 0.88, 'support': 25}, 'accuracy': 0.8722222222222222, 'macro avg': {'precision': 0.6720216135293349, 'recall': 0.8716020677045523, 'f1-score': 0.7156383615235642, 'support': 360}, 'weighted avg': {'precision': 0.8787030939031133, 'recall': 0.8722222222222222, 'f1-score': 0.8741796334432392, 'support

In [95]:
print(matthews_corrcoef(y_test,preds))

0.8120385307431411


In [126]:
unique, counts = np.unique(preds, return_counts=True)
print(unique)
cm = confusion_matrix(y_test,preds,labels=unique)
print(cm)
FP = np.sum(cm, axis=0) - np.diag(cm)  
FN = np.sum(cm, axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm[:].sum() - (FP + FN + TP)

print(FP)
print(FN)
print(TP)
print(TN)

recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)
print(recall)
print(precision)
f1score = 2*precision*recall/(precision+recall)
print(f1score)
mcc = matthews_corrcoef(y_test,preds)
print(mcc)
new_precision = TP/(TP+FN)
new_recall = TP/(TP+FP)
new_f1score = TP/(TP+0.5*(FP+FN))
new_mcc = (TP*TN-FP*FN)/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
print(new_precision)
print(new_recall)
print(new_f1score)
print(new_mcc)

['ID' 'NOD' 'OD' 'OD-Brit' 'OD-Vic' 'UD']
[[164   7   2   0   0   1]
 [ 11  14   3   0   0   0]
 [  3   3  83   0   0   0]
 [  0   1   0   1   0   1]
 [  0   3   0   0  34   0]
 [  3   1   0   0   0  21]]
[17 15  5  0  0  2]
[10 14  6  2  3  4]
[164  14  83   1  34  21]
[165 313 262 353 319 329]
[0.94252874 0.5        0.93258427 0.33333333 0.91891892 0.84      ]
[0.90607735 0.48275862 0.94318182 1.         1.         0.91304348]
[0.92394366 0.49122807 0.93785311 0.5        0.95774648 0.875     ]
0.8232274888979061
[0.94252874 0.5        0.93258427 0.33333333 0.91891892 0.84      ]
[0.90607735 0.48275862 0.94318182 1.         1.         0.91304348]
[0.92394366 0.49122807 0.93785311 0.5        0.95774648 0.875     ]
[0.84902831 0.44704937 0.91731916 0.57572163 0.9541266  0.86684608]


In [125]:
FP = np.asarray([144 , 1 ,253 , 67  ,20 ,  8 ,  0], dtype=np.int)
FN = np.asarray([  0 ,  0 ,  0 ,  0 ,  0 , 47 ,446], dtype=np.int)
TP = np.asarray([1, 1, 1, 1, 1, 281, 48], dtype=np.int)
TN = np.asarray([678 ,821 ,569 ,755 ,802, 486, 328], dtype=np.int)
precision = TP/(TP+FN)
recall = TP/(TP+FP)
f1score = TP/(TP+0.5*(FP+FN))
mcc = (TP*TN-FP*FN)/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

print(precision)
print(recall)
print(f1score)
print(mcc)


[1.         1.         1.         1.         1.         0.85670732
 0.09716599]
[0.00689655 0.5        0.00393701 0.01470588 0.04761905 0.97231834
 1.        ]
[0.01369863 0.66666667 0.00784314 0.02898551 0.09090909 0.910859
 0.17712177]
[0.07542146 0.70667654 0.05220395 0.1162206  0.21554682 0.86204969
 0.20291941]


In [86]:
result = {}
result['ID']={}
result['ID']['precision']=[]
result['ID']['precision'].append(0.91)
result['ID']['precision'].append(0.80)
result['ID']['precision'] = sum(result['ID']['precision'])/len(result['ID']['precision'])
print(result)

{'ID': {'precision': 0.855}}


In [89]:
matchers = ['f1s','precision','recall','fdc','mcc']
if 'f1s' in matchers:
    print('f1s')

f1s


['ID' 'NDOD' 'NOD' 'OD' 'OD-Brit' 'OD-Vic' 'UD']


In [39]:
lda = LinearDiscriminantAnalysis(n_components=3)
lda_val = lda.fit_transform(x_smote_tl, y_smote_tl)

X = lda_val
y = y_smote_tl

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
preds = rf.predict(X_test)
print(classification_report(preds,y_test))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test, average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test, average='weighted'))))

fileName = "sampling_smote_tl.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.68      0.68      0.68       177
        NDOD       1.00      1.00      1.00       177
         NOD       0.79      0.72      0.75       192
          OD       0.56      0.66      0.60       148
     OD-Brit       0.99      1.00      0.99       175
      OD-Vic       0.94      0.88      0.91       189
          UD       0.97      0.97      0.97       175

    accuracy                           0.85      1233
   macro avg       0.85      0.84      0.84      1233
weighted avg       0.85      0.85      0.85      1233

Precision:0.8532836721015615
Recall:0.8467153284671532
F1 Score:0.8490196637104973


In [127]:
lda = LinearDiscriminantAnalysis(n_components=3)
lda_val = lda.fit_transform(vector_val, vector_cat)

X = lda_val
y = vector_cat

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
preds = rf.predict(X_test)
print(classification_report(preds,y_test))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test, average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test, average='weighted'))))

fileName = "sampling_none.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.94      0.91      0.93       183
        NDOD       0.33      1.00      0.50         1
         NOD       0.36      0.52      0.43        23
          OD       0.89      0.85      0.87        97
     OD-Brit       0.00      0.00      0.00         0
      OD-Vic       0.93      0.86      0.89        43
          UD       0.93      0.84      0.88        31

    accuracy                           0.86       378
   macro avg       0.63      0.71      0.64       378
weighted avg       0.89      0.86      0.87       378

Precision:0.8898815414575845
Recall:0.8597883597883598
F1 Score:0.872934316549428


/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMe

In [36]:
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [128]:
def stratified_kfold_score(clf,X,y,n_fold):
    X,y = X,y.values
    strat_kfold = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=1)
    accuracy_list = []

    for train_index, test_index in strat_kfold.split(X, y):
        x_train_fold, x_test_fold = X[train_index], X[test_index]
        y_train_fold, y_test_fold = y[train_index], y[test_index]
        clf.fit(x_train_fold, y_train_fold)
        preds = clf.predict(x_test_fold)
        accuracy_test = accuracy_score(preds,y_test_fold)
        print(accuracy_test)
        accuracy_list.append(accuracy_test)

    return np.array(accuracy_list).mean()

    
def bo_params_rf(max_samples,n_estimators,min_impurity_decrease,min_samples_leaf,min_samples_split,max_depth,X,y):
        
    params = {
        'max_samples': max_samples,
        'max_depth': int(max_depth),
        'min_impurity_decrease':min_impurity_decrease,
        'min_samples_leaf':int(min_samples_leaf),
        'min_samples_split':int(min_samples_split),
        'n_estimators':int(n_estimators)
    }
    clf = RandomForestClassifier(max_samples=params['max_samples'],max_depth=params['max_depth'],min_impurity_decrease=params['min_impurity_decrease'],min_samples_leaf=params['min_samples_leaf'],min_samples_split=params['min_samples_split'],n_estimators=params['n_estimators'])
    score = stratified_kfold_score(clf,X, y,5)
    return score

def bo_params_gbdt(n_estimators,learning_rate,max_depth,min_samples_leaf,min_samples_split):
        
    params = {
        'learning_rate': learning_rate,
        'max_depth':int(max_depth),
        'min_samples_leaf':int(min_samples_leaf),
        'min_samples_split':int(min_samples_split),
        'n_estimators':int(n_estimators)
    }
    clf = GradientBoostingClassifier(learning_rate=params['learning_rate'],max_depth=params['max_depth'],min_samples_leaf=params['min_samples_leaf'],min_samples_split=params['min_samples_split'],n_estimators=params['n_estimators'])
    score = stratified_kfold_score(clf,X_train, y_train,5)
    return score

In [131]:
rf_bo = BayesianOptimization(bo_params_rf, {
                                              'max_samples':(0.5,1),
                                              'max_depth':(1,200),
                                              'min_impurity_decrease':(0,0.5),
                                              'min_samples_leaf':(1,200),
                                              'min_samples_split':(2,400),
                                              'n_estimators':(100,200)
                                             })

In [54]:
results = rf_bo.maximize(n_iter=200, init_points=20,acq='ei')

|   iter    |  target   | max_depth | max_sa... | min_im... | min_sa... | min_sa... | n_esti... |
-------------------------------------------------------------------------------------------------
|  1        |  0.1434   |  169.7    |  0.8177   |  0.1853   |  67.38    |  48.18    |  165.4    |
|  2        |  0.6948   |  60.47    |  0.725    |  0.05249  |  195.2    |  157.7    |  137.2    |
|  3        |  0.143    |  198.9    |  0.8433   |  0.3394   |  108.2    |  52.34    |  171.6    |
|  4        |  0.7227   |  43.9     |  0.969    |  0.03465  |  178.0    |  49.25    |  140.0    |
|  5        |  0.143    |  78.48    |  0.7509   |  0.4424   |  109.7    |  125.5    |  157.8    |
|  6        |  0.7651   |  104.5    |  0.9018   |  0.002188 |  146.9    |  74.48    |  184.8    |
|  7        |  0.1427   |  28.41    |  0.6199   |  0.2901   |  153.0    |  2.247    |  148.2    |
|  8        |  0.143    |  22.78    |  0.5586   |  0.2901   |  151.4    |  276.1    |  178.2    |
|  9        |  0.142

In [55]:
params = rf_bo.max['params']
params['max_depth']=  int(params['max_depth'])
params['min_samples_leaf']=  int(params['min_samples_leaf'])
params['min_samples_split']=  int(params['min_samples_split'])
params['n_estimators']= int(params['n_estimators'])
print(params)

{'max_depth': 94, 'max_samples': 0.9882223767788391, 'min_impurity_decrease': 0.0016126928268648255, 'min_samples_leaf': 42, 'min_samples_split': 258, 'n_estimators': 113}


In [57]:
rf_v1 = RandomForestClassifier(max_samples=params['max_samples'],max_depth=params['max_depth'],min_samples_leaf=params['min_samples_leaf'],min_samples_split=params['min_samples_split'],n_estimators=params['n_estimators'])

In [58]:
rf_v1.fit(X_train,y_train)
preds = rf_v1.predict(X_test)
print(classification_report(preds,y_test))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test,average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test,average='weighted'))))
fileName = "sampling_smote_tl_BO.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.68      0.58      0.63       206
        NDOD       1.00      1.00      1.00       177
         NOD       0.76      0.60      0.67       221
          OD       0.30      0.56      0.39        93
     OD-Brit       0.97      1.00      0.99       172
      OD-Vic       0.93      0.85      0.89       191
          UD       0.95      0.96      0.95       173

    accuracy                           0.80      1233
   macro avg       0.80      0.79      0.79      1233
weighted avg       0.83      0.80      0.81      1233

Precision:0.8274407422641371
Recall:0.797242497972425
F1 Score:0.8067599076520422


In [59]:
gbdt = GradientBoostingClassifier()
gbdt.fit(X_train,y_train)
preds = gbdt.predict(X_test)
print(classification_report(preds,y_test))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test, average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test, average='weighted'))))

              precision    recall  f1-score   support

          ID       0.61      0.63      0.62       172
        NDOD       1.00      1.00      1.00       177
         NOD       0.70      0.62      0.66       197
          OD       0.48      0.56      0.52       151
     OD-Brit       0.99      0.99      0.99       176
      OD-Vic       0.93      0.88      0.90       185
          UD       0.96      0.96      0.96       175

    accuracy                           0.81      1233
   macro avg       0.81      0.81      0.81      1233
weighted avg       0.82      0.81      0.81      1233

Precision:0.8164514783103178
Recall:0.8102189781021898
F1 Score:0.812486947174821


In [47]:
gbdt.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [61]:
gbdt_bo = BayesianOptimization(bo_params_gbdt, {
                                              'learning_rate':(0.001,10),
                                              'max_depth':(1,200),
                                              'min_samples_leaf':(1,200),
                                              'min_samples_split':(2,400),
                                              'n_estimators':(100,200)
                                             })

In [62]:
results = gbdt_bo.maximize(n_iter=200, init_points=20,acq='ei')

|   iter    |  target   | learni... | max_depth | min_sa... | min_sa... | n_esti... |
-------------------------------------------------------------------------------------
|  1        |  0.435    |  4.821    |  62.8     |  85.31    |  70.36    |  143.9    |
|  2        |  0.2529   |  6.644    |  105.9    |  39.02    |  323.2    |  190.8    |
|  3        |  0.4478   |  5.03     |  70.97    |  61.13    |  54.82    |  159.7    |
|  4        |  0.3086   |  3.842    |  65.88    |  193.0    |  96.05    |  169.8    |
|  5        |  0.4318   |  4.118    |  146.7    |  60.85    |  23.25    |  175.0    |
|  6        |  0.3545   |  3.75     |  84.16    |  196.9    |  269.5    |  175.9    |
|  7        |  0.7909   |  0.5298   |  194.0    |  164.4    |  301.5    |  194.8    |
|  8        |  0.3477   |  1.366    |  118.3    |  197.8    |  313.4    |  113.6    |
|  9        |  0.4343   |  9.645    |  61.87    |  64.48    |  165.3    |  185.6    |
|  10       |  0.7947   |  0.2601   |  84.26    |  85.

In [63]:
params = gbdt_bo.max['params']

params['max_depth']=  int(params['max_depth'])
params['min_samples_leaf']=  int(params['min_samples_leaf'])
params['min_samples_split']=  int(params['min_samples_split'])
params['n_estimators']= int(params['n_estimators'])
print(params)

{'learning_rate': 0.5433990284529154, 'max_depth': 17, 'min_samples_leaf': 88, 'min_samples_split': 305, 'n_estimators': 187}


In [65]:
gbdt_v1 = GradientBoostingClassifier(learning_rate=params['learning_rate'],max_depth=params['max_depth'],min_samples_leaf=params['min_samples_leaf'],min_samples_split=params['min_samples_split'],n_estimators=params['n_estimators'])

gbdt_v1.fit(X_train,y_train)
preds = gbdt_v1.predict(X_test)
print(classification_report(preds,y_test))
print("Precision:{}".format(precision_score(preds,y_test,average='weighted')))
print("Recall:{}".format(recall_score(preds,y_test,average='weighted')))
print("F1 Score:{}".format((f1_score(preds,y_test,average='weighted'))))

fileName = "sampling_smote_tl_BO_gbdt.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.57      0.61      0.59       165
        NDOD       1.00      1.00      1.00       177
         NOD       0.71      0.64      0.67       194
          OD       0.49      0.51      0.50       167
     OD-Brit       0.99      1.00      1.00       176
      OD-Vic       0.91      0.88      0.89       182
          UD       0.96      0.98      0.97       172

    accuracy                           0.80      1233
   macro avg       0.80      0.80      0.80      1233
weighted avg       0.81      0.80      0.81      1233

Precision:0.8076219524858645
Recall:0.8045417680454177
F1 Score:0.8056082202279264


In [117]:
knn = KNeighborsClassifier(n_neighbors=10, metric='euclidean')

knn.fit(X_train,y_train)
preds = knn.predict(X_test)

print(classification_report(preds,y_test))

fileName = "sampling_smote_tl_knn.csv"
df = pd.DataFrame(classification_report(y_test, preds, output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.94      0.90      0.92       182
        NDOD       0.00      0.00      0.00         0
         NOD       0.50      0.47      0.48        30
          OD       0.93      0.93      0.93        89
     OD-Brit       0.33      1.00      0.50         1
      OD-Vic       0.92      0.97      0.94        35
          UD       0.84      0.91      0.87        23

    accuracy                           0.88       360
   macro avg       0.64      0.74      0.67       360
weighted avg       0.89      0.88      0.89       360



/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMe

In [115]:
FP = [0,0,0]
map(sum, zip(FP,[1,2,3]))
print(FP)
map(sum, zip(FP,[1,2,3]))
print(FP)



[0, 0, 0]
[0, 0, 0]


In [80]:
svmClf = svm.SVC(kernel='sigmoid', random_state=0)

svmClf.fit(X_train,y_train)
preds = svmClf.predict(X_test)

print(classification_report(preds,y_test))

fileName = "sampling_smote_tl_svm.csv"
df = pd.DataFrame(classification_report(preds,y_test,output_dict=True)).transpose()
df.to_csv(fileName)

              precision    recall  f1-score   support

          ID       0.58      0.59      0.59       175
        NDOD       1.00      0.99      0.99       179
         NOD       0.75      0.53      0.62       248
          OD       0.30      0.55      0.39        96
     OD-Brit       1.00      0.88      0.94       201
      OD-Vic       0.80      0.87      0.83       163
          UD       0.94      0.96      0.95       171

    accuracy                           0.77      1233
   macro avg       0.77      0.77      0.76      1233
weighted avg       0.80      0.77      0.78      1233

